<a href="https://colab.research.google.com/github/PawanKumar1216/northstar-databases-analytics-assignment/blob/main/notebooks/08_Query_Optimisation_Strategies.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 08 Query Optimisation Strategies

## NorthStar Urban Mobility and Logistics

This notebook demonstrates the use of **query optimisation strategies in MongoDB** for the NorthStar Urban Mobility and Logistics case study.

As operational datasets grow, inefficient queries can increase response time and reduce the usefulness of real-time logistics analysis. MongoDB provides indexing and query-plan analysis tools that help improve retrieval efficiency by reducing the number of documents scanned during query execution.

### Main objectives
- Connect Python to the MongoDB Atlas database
- Examine existing collections and indexes
- Run baseline queries before optimisation
- Use `explain()` to inspect query execution plans
- Create single-field and compound indexes
- Compare query behaviour before and after indexing
- Demonstrate practical optimisation strategies for delivery operations

In [1]:
# Install the MongoDB Python driver required for this notebook

!pip install pymongo

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.8/1.8 MB 21.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 331.1/331.1 kB 23.8 MB/s eta 0:00:00


In [2]:
# Import the libraries required for MongoDB query optimisation

from pymongo import MongoClient, ASCENDING
from getpass import getpass
from urllib.parse import quote_plus
from pprint import pprint

print("Libraries imported successfully.")

Libraries imported successfully.


## 1. Connecting to the MongoDB Atlas Database

The notebook connects securely to the same MongoDB Atlas database created in the previous notebook. The password is entered privately at runtime and is not stored inside the notebook, which protects the database credentials when the project is uploaded to GitHub.

In [3]:
# Enter MongoDB Atlas credentials securely and build the connection string

username = "northstar_user"
password = quote_plus(getpass("Enter your MongoDB Atlas password: "))

mongo_uri = f"mongodb+srv://{username}:{password}@cluster0.uifgv62.mongodb.net/?appName=Cluster0"

print("MongoDB connection details entered securely.")

Enter your MongoDB Atlas password: ··········
MongoDB connection details entered securely.


In [4]:
# Connect to MongoDB Atlas and select the project database

client = MongoClient(mongo_uri)

# Test the connection
client.admin.command("ping")

# Select the project database and deliveries collection
db = client["northstar_logistics"]
deliveries_collection = db["deliveries"]

print("Successfully connected to MongoDB Atlas.")
print("Database selected: northstar_logistics")
print("Collection selected: deliveries")

Successfully connected to MongoDB Atlas.
Database selected: northstar_logistics
Collection selected: deliveries


## 2. Inspecting the Collection Before Optimisation

Before applying any optimisation strategies, the deliveries collection is inspected to confirm that the data is available and to review the indexes that already exist. This establishes the starting point for the query optimisation process.

In [5]:
# Confirm the number of documents available in the deliveries collection

delivery_count = deliveries_collection.count_documents({})

print("Total documents in deliveries collection:", delivery_count)

Total documents in deliveries collection: 950


In [6]:
# Inspect the indexes that currently exist before creating any new optimisation indexes

print("Existing indexes before optimisation:")
for index in deliveries_collection.list_indexes():
    pprint(index)

Existing indexes before optimisation:
SON([('v', 2), ('key', SON([('_id', 1)])), ('name', '_id_')])


## 3. Baseline Query Before Indexing

A baseline query is first tested before creating any new indexes. The query searches for delayed deliveries, which is a realistic operational request because logistics managers may need to quickly identify deliveries requiring attention.

The `explain()` method is used to inspect how MongoDB executes the query. At this stage, because there is no index on `delivery_status`, MongoDB is expected to scan the full collection.

In [7]:
# Run a baseline query plan before creating an index on delivery_status

baseline_status_query = deliveries_collection.find(
    {"delivery_status": "Delayed"}
)

baseline_status_explain = baseline_status_query.explain()

print("Baseline query plan before indexing delivery_status:")
print("Winning plan stage:",
      baseline_status_explain["queryPlanner"]["winningPlan"]["stage"])
print("Documents examined:",
      baseline_status_explain["executionStats"]["totalDocsExamined"])
print("Keys examined:",
      baseline_status_explain["executionStats"]["totalKeysExamined"])
print("Documents returned:",
      baseline_status_explain["executionStats"]["nReturned"])

Baseline query plan before indexing delivery_status:
Winning plan stage: COLLSCAN
Documents examined: 950
Keys examined: 0
Documents returned: 202


## 4. Creating a Single-Field Index

To optimise searches by delivery outcome, a single-field ascending index is created on `delivery_status`. This index allows MongoDB to locate matching delivery records more efficiently instead of scanning every document in the collection.

In [8]:
# Create a single-field index on delivery_status

deliveries_collection.create_index(
    [("delivery_status", ASCENDING)],
    name="idx_delivery_status"
)

print("Single-field index created on delivery_status.")

Single-field index created on delivery_status.


In [9]:
# Run the same query again after creating the delivery_status index

optimised_status_query = deliveries_collection.find(
    {"delivery_status": "Delayed"}
)

optimised_status_explain = optimised_status_query.explain()

print("Query plan after indexing delivery_status:")
print("Winning plan stage:",
      optimised_status_explain["queryPlanner"]["winningPlan"]["stage"])
print("Input stage:",
      optimised_status_explain["queryPlanner"]["winningPlan"]["inputStage"]["stage"])
print("Documents examined:",
      optimised_status_explain["executionStats"]["totalDocsExamined"])
print("Keys examined:",
      optimised_status_explain["executionStats"]["totalKeysExamined"])
print("Documents returned:",
      optimised_status_explain["executionStats"]["nReturned"])

Query plan after indexing delivery_status:
Winning plan stage: FETCH
Input stage: IXSCAN
Documents examined: 202
Keys examined: 202
Documents returned: 202


### Interpretation of the Single-Field Index Result

Before indexing, MongoDB used a **collection scan (`COLLSCAN`)**, which required all **950 delivery documents** to be examined in order to return **202 delayed deliveries**.

After creating the `delivery_status` index, the query used an **index scan (`IXSCAN`)** and examined only the **202 matching indexed records**. This demonstrates that indexing improves query efficiency by reducing unnecessary document scanning, which becomes increasingly important as operational datasets grow.

## 5. Baseline Query for Multiple Conditions

Logistics managers may also need to identify deliveries that are both **delayed** and associated with a high number of manual route overrides. A query using more than one condition is therefore tested before creating a compound index.

This provides a baseline for evaluating whether a compound index can improve queries that filter on multiple operational fields.

In [10]:
# Run a baseline multi-condition query before creating a compound index

baseline_compound_query = deliveries_collection.find(
    {
        "delivery_status": "Delayed",
        "manual_route_override_count": {"$gte": 3}
    }
)

baseline_compound_explain = baseline_compound_query.explain()

print("Baseline multi-condition query plan before compound indexing:")
print("Winning plan stage:",
      baseline_compound_explain["queryPlanner"]["winningPlan"]["stage"])
print("Input stage:",
      baseline_compound_explain["queryPlanner"]["winningPlan"]["inputStage"]["stage"])
print("Documents examined:",
      baseline_compound_explain["executionStats"]["totalDocsExamined"])
print("Keys examined:",
      baseline_compound_explain["executionStats"]["totalKeysExamined"])
print("Documents returned:",
      baseline_compound_explain["executionStats"]["nReturned"])


Baseline multi-condition query plan before compound indexing:
Winning plan stage: FETCH
Input stage: IXSCAN
Documents examined: 202
Keys examined: 202
Documents returned: 23


## 6. Creating a Compound Index

A compound index is created on both `delivery_status` and `manual_route_override_count`. This index is suitable for queries that filter by delivery status first and then by route override count, allowing MongoDB to narrow the search more precisely for multi-condition operational queries.

In [11]:
# Create a compound index for multi-condition delivery queries

deliveries_collection.create_index(
    [
        ("delivery_status", ASCENDING),
        ("manual_route_override_count", ASCENDING)
    ],
    name="idx_status_override_count"
)

print("Compound index created on delivery_status and manual_route_override_count.")

Compound index created on delivery_status and manual_route_override_count.


In [12]:
# Run the same multi-condition query again after creating the compound index

optimised_compound_query = deliveries_collection.find(
    {
        "delivery_status": "Delayed",
        "manual_route_override_count": {"$gte": 3}
    }
)

optimised_compound_explain = optimised_compound_query.explain()

print("Query plan after compound indexing:")
print("Winning plan stage:",
      optimised_compound_explain["queryPlanner"]["winningPlan"]["stage"])
print("Input stage:",
      optimised_compound_explain["queryPlanner"]["winningPlan"]["inputStage"]["stage"])
print("Documents examined:",
      optimised_compound_explain["executionStats"]["totalDocsExamined"])
print("Keys examined:",
      optimised_compound_explain["executionStats"]["totalKeysExamined"])
print("Documents returned:",
      optimised_compound_explain["executionStats"]["nReturned"])

Query plan after compound indexing:
Winning plan stage: FETCH
Input stage: IXSCAN
Documents examined: 23
Keys examined: 23
Documents returned: 23


### Interpretation of the Compound Index Result

Before the compound index was created, MongoDB used the existing `delivery_status` index and examined **202 delayed delivery records** before applying the second condition on `manual_route_override_count`.

After creating the compound index on both `delivery_status` and `manual_route_override_count`, MongoDB examined only the **23 documents** that matched both conditions. This shows that a compound index is more efficient for queries that frequently filter on multiple fields together, because it reduces additional filtering after the first condition has already been applied.

## 7. Reviewing Indexes After Optimisation

After creating the optimisation indexes, the collection is inspected again to confirm that MongoDB now contains the default `_id` index, the single-field index, and the compound index created for the delivery queries.

In [13]:
# Inspect all indexes available after optimisation

print("Indexes after optimisation:")
for index in deliveries_collection.list_indexes():
    pprint(index)

Indexes after optimisation:
SON([('v', 2), ('key', SON([('_id', 1)])), ('name', '_id_')])
SON([('v', 2), ('key', SON([('delivery_status', 1)])), ('name', 'idx_delivery_status')])
SON([('v', 2), ('key', SON([('delivery_status', 1), ('manual_route_override_count', 1)])), ('name', 'idx_status_override_count')])


## 8. Summary Comparison of Query Optimisation Results

The table below summarises the effect of the indexing strategies applied in this notebook. It shows how MongoDB reduced the number of documents examined while returning the same results, demonstrating improved query efficiency.

In [14]:
# Create a summary table comparing query performance before and after indexing

import pandas as pd

optimisation_summary = pd.DataFrame({
    "Query Type": [
        "Filter by delivery_status",
        "Filter by delivery_status and manual_route_override_count"
    ],
    "Before Indexing": [
        "COLLSCAN: 950 documents examined",
        "Single-field index only: 202 documents examined"
    ],
    "After Indexing": [
        "IXSCAN: 202 documents examined",
        "Compound index: 23 documents examined"
    ],
    "Documents Returned": [
        202,
        23
    ]
})

display(optimisation_summary)

,Query Type,Before Indexing,After Indexing,Documents Returned
0,Filter by delivery_status,COLLSCAN: 950 documents examined,IXSCAN: 202 documents examined,202
1,Filter by delivery_status and manual_route_ove...,Single-field index only: 202 documents examined,Compound index: 23 documents examined,23


## 9. Key Optimisation Findings

The optimisation tests produced clear evidence that indexing improved MongoDB query efficiency:

- Without a suitable index, the delayed-delivery query used a **collection scan (`COLLSCAN`)** and examined all **950 documents**.
- After creating a single-field index on `delivery_status`, the same query used an **index scan (`IXSCAN`)** and examined only **202 documents**.
- For the multi-condition query, the existing single-field index still required MongoDB to examine **202 delayed-delivery records** before applying the second condition.
- After creating the compound index on `delivery_status` and `manual_route_override_count`, MongoDB examined only the **23 matching documents**.
- The results show that index design should be based on the fields that are frequently filtered together in real operational queries.
- In the NorthStar case study, these strategies are particularly useful for quickly identifying delayed deliveries and high-override cases that may require management attention.

## 10. Conclusion

This notebook demonstrated how MongoDB query optimisation can be implemented using Python and PyMongo for the NorthStar Urban Mobility and Logistics case study.

The analysis showed that a query without a suitable index required MongoDB to scan the full deliveries collection, while the creation of a single-field index on `delivery_status` reduced the number of documents examined from **950** to **202**. A compound index on `delivery_status` and `manual_route_override_count` further improved the multi-condition query by reducing the number of documents examined from **202** to **23**.

Overall, the results confirm that well-designed indexes improve query efficiency, reduce unnecessary document scanning, and support faster operational decision-making. For a logistics organisation such as NorthStar, this is valuable for monitoring delayed deliveries, identifying high-override cases, and maintaining efficient database performance as data volumes increase.