-- NorthStar Urban Mobility and Logistics
-- Analytical SQL queries for delivery operations

USE northstar_logistics;


-- 1. View all delivery records with customer, driver, vehicle, and route details
SELECT
    d.delivery_id,
    c.customer_name,
    c.city,
    dr.driver_name,
    v.registration_number,
    v.vehicle_type,
    r.start_location,
    r.end_location,
    d.delivery_date,
    d.delivery_status,
    d.delivery_cost
FROM deliveries d
INNER JOIN customers c
    ON d.customer_id = c.customer_id
INNER JOIN drivers dr
    ON d.driver_id = dr.driver_id
INNER JOIN vehicles v
    ON d.vehicle_id = v.vehicle_id
INNER JOIN routes r
    ON d.route_id = r.route_id
ORDER BY d.delivery_date;


-- 2. Count deliveries by delivery status
SELECT
    delivery_status,
    COUNT(*) AS total_deliveries
FROM deliveries
GROUP BY delivery_status
ORDER BY total_deliveries DESC;


-- 3. Calculate total and average delivery cost
SELECT
    COUNT(*) AS total_deliveries,
    SUM(delivery_cost) AS total_delivery_cost,
    AVG(delivery_cost) AS average_delivery_cost
FROM deliveries;


-- 4. Find deliveries that were delayed
SELECT
    d.delivery_id,
    c.customer_name,
    dr.driver_name,
    d.delivery_date,
    d.delivery_status,
    d.delivery_cost
FROM deliveries d
INNER JOIN customers c
    ON d.customer_id = c.customer_id
INNER JOIN drivers dr
    ON d.driver_id = dr.driver_id
WHERE d.delivery_status = 'Delayed'
ORDER BY d.delivery_date;


-- 5. Count deliveries handled by each driver
SELECT
    dr.driver_name,
    COUNT(d.delivery_id) AS total_deliveries
FROM drivers dr
LEFT JOIN deliveries d
    ON dr.driver_id = d.driver_id
GROUP BY dr.driver_id, dr.driver_name
ORDER BY total_deliveries DESC;


-- 6. Calculate revenue generated by each driver
SELECT
    dr.driver_name,
    SUM(d.delivery_cost) AS total_revenue
FROM drivers dr
INNER JOIN deliveries d
    ON dr.driver_id = d.driver_id
GROUP BY dr.driver_id, dr.driver_name
ORDER BY total_revenue DESC;


-- 7. Identify the most frequently used routes
SELECT
    r.start_location,
    r.end_location,
    COUNT(d.delivery_id) AS route_usage_count
FROM routes r
INNER JOIN deliveries d
    ON r.route_id = d.route_id
GROUP BY r.route_id, r.start_location, r.end_location
ORDER BY route_usage_count DESC;


-- 8. Calculate average delivery cost by city
SELECT
    c.city,
    COUNT(d.delivery_id) AS total_deliveries,
    AVG(d.delivery_cost) AS average_delivery_cost
FROM customers c
INNER JOIN deliveries d
    ON c.customer_id = d.customer_id
GROUP BY c.city
ORDER BY average_delivery_cost DESC;


-- 9. Show active drivers and their assigned deliveries
SELECT
    dr.driver_name,
    dr.employment_status,
    COUNT(d.delivery_id) AS assigned_deliveries
FROM drivers dr
LEFT JOIN deliveries d
    ON dr.driver_id = d.driver_id
WHERE dr.employment_status = 'Active'
GROUP BY dr.driver_id, dr.driver_name, dr.employment_status
ORDER BY assigned_deliveries DESC;


-- 10. Show delivery performance by vehicle type
SELECT
    v.vehicle_type,
    COUNT(d.delivery_id) AS total_deliveries,
    SUM(d.delivery_cost) AS total_delivery_cost,
    AVG(d.delivery_cost) AS average_delivery_cost
FROM vehicles v
INNER JOIN deliveries d
    ON v.vehicle_id = d.vehicle_id
GROUP BY v.vehicle_type
ORDER BY total_deliveries DESC;